- name: Check if we need to install pypy
  shell: "{{ ansible_python_interpreter }} -c 'import platform;print(platform.python_implementation())'"
  register: need_pypy
  ignore_errors: True
  changed_when: false

- name: Run bootstrap.sh
  script: bootstrap.sh "{{ pypy_version }}" "{{ pypy_arch }}" "{{ pypy_bin_path }}" "{{ pypy_home }}" "{{ pypy_mirror }}" "{{ pypy_wget_extra }}"
  when: need_pypy is failed or need_pypy.stdout != "PyPy"

- name: Check if we need to install pip
  shell: "{{ pypy_bin_path }}/python -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: false

- name: Copy get-pip.py
  copy: src=get-pip.py dest={{ pypy_home }}/get-pip.py
  when: need_pip is failed

- name: Install pip
  shell: "{{ pypy_bin_path }}/python  {{ pypy_home }}/get-pip.py"
  when: need_pip is failed

- name: Remove get-pip.py
  file: path={{ pypy_home }}/get-pip.py state=absent
  when: need_pip is failed

- name: Install pip launcher
  shell: "ln -snf {{pypy_home}}/bin/pip {{ pypy_bin_path }}/pip"
  when: need_pip is failed

- name: Install docker-py@pip
  shell: "{{ pypy_bin_path }}/pip install docker-py"
  register: pip_docker_py
  when: pypy_pip_packages.docker_py
